### PR TITLE
Configuration to use throttle proxy

### PR DESCRIPTION
**Pull request by wlongabaugh**
This installs the necessary config file to get the OHIF Viewer pointing at the throttle proxy

### CODE REVIEW

**Comment by G-White-ISB** [comment]
I can check it out tomorrow.
George

**Comment by G-White-ISB** [comment]
I am getting ' No 'Access-Control-Allow-Origin' header is present on the requested resource.' when running the viewer locally and attempting to fetch the dicom resources from the proxy. The responses should include an 'Access-Control-Allow-Origin' header. For local development the header value should be 'http://localhost:8085'. For the deployed app its 'https://idc-dev.appspot.com/'.

**Comment by wlongabaugh** [comment]
Could you provide a screen shot? The proxy is configured to return that header, but only in an OPTIONS CORS preflight request. What browser are you using?

**Comment by wlongabaugh** [comment]
OptionHeadersProxy

**Comment by G-White-ISB** [comment]
Using chrome
ohif_cors_issue

**Comment by wlongabaugh** [comment]
Sigh. I'm using Chrome too, and those headers being sent in a CORS OPTIONS preflight is all that is needed. Will investigate. On the plus side, you *are* talking to the proxy.

**Comment by wlongabaugh** [comment]
OK, I was limiting the inclusion of those headers to only OPTIONS requests. Looks like I need to broaden to include GET requests as well. Since we *are* talking to the proxy, the config file should be good to include as I work to fix the proxy.

**Comment by G-White-ISB** [comment]
Its working this morning. Loading a specific series (vs a study) now works too.

**Pull request merged**
